import Head from 'next/head';
import Link from 'next/link';
import { useState, useEffect } from 'react';
import QuickExitButton from '@/src/components/QuickExitButton';
import { useCommunity } from '@/src/contexts/CommunityContext';

/**
 * Community Forum List Page
 * 
 * SECURITY: This page displays forum threads with anonymized author IDs.
 * All usernames are generated by the CommunityContext and are non-traceable.
 * 
 * In production:
 * 1. Implement server-side validation to ensure no real names appear
 * 2. Use pagination to limit data exposure
 * 3. Implement rate limiting on post creation
 * 4. Store posts with only anonymous IDs, never linked to user accounts
 */
interface ForumThread {
  id: string;
  title: string;
  authorId: string; // SECURITY: This is an anonymized ID, not a real username
  createdAt: string;
  replyCount: number;
}

export default function CommunityForum() {
  const { anonymousId } = useCommunity();
  const [threads, setThreads] = useState<ForumThread[]>([]);
  const [loading, setLoading] = useState(true);
  const [currentPage, setCurrentPage] = useState(1);
  const threadsPerPage = 10;

  useEffect(() => {
    // SECURITY: This is a placeholder. In production:
    // 1. Fetch threads from /api/forum endpoint
    // 2. Server must validate and sanitize all data
    // 3. Never return any identifying information
    // 4. Implement pagination server-side
    
    // Placeholder data
    const mockThreads: ForumThread[] = [
      {
        id: '1',
        title: 'Welcome to the Community',
        authorId: 'anon_abc123_xyz',
        createdAt: new Date().toISOString(),
        replyCount: 5,
      },
      {
        id: '2',
        title: 'Resources and Support',
        authorId: 'anon_def456_uvw',
        createdAt: new Date().toISOString(),
        replyCount: 12,
      },
    ];
    
    setTimeout(() => {
      setThreads(mockThreads);
      setLoading(false);
    }, 500);
  }, [currentPage]);

  return (
    <>
      <Head>
        <title>Community Forum - SafeHarbor</title>
        <meta name="robots" content="noindex, nofollow" />
      </Head>

      <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100">
        <div className="fixed top-4 right-4 z-50">
          <QuickExitButton />
        </div>

        <div className="container mx-auto px-4 py-16">
          <div className="max-w-6xl mx-auto">
            <div className="flex justify-between items-center mb-8">
              <h1 className="text-4xl font-bold text-gray-900">
                Community Forum
              </h1>
              <Link
                href="/community/new"
                className="bg-blue-600 hover:bg-blue-700 text-white font-semibold py-2 px-4 rounded-md transition-colors"
              >
                New Thread
              </Link>
            </div>

            {/* Security Notice */}
            <div className="bg-blue-50 border-l-4 border-blue-400 p-4 rounded mb-6">
              <p className="text-sm text-blue-800">
                <strong>Privacy:</strong> All posts are anonymous. Your current anonymous ID: <code className="bg-blue-100 px-1 rounded">{anonymousId}</code>
              </p>
            </div>

            {loading ? (
              <div className="text-center py-12">
                <p className="text-gray-600">Loading threads...</p>
              </div>
            ) : (
              <>
                <div className="bg-white rounded-lg shadow-md overflow-hidden">
                  <table className="w-full">
                    <thead className="bg-gray-100">
                      <tr>
                        <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                          Title
                        </th>
                        <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                          Author
                        </th>
                        <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                          Replies
                        </th>
                        <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                          Date
                        </th>
                      </tr>
                    </thead>
                    <tbody className="bg-white divide-y divide-gray-200">
                      {threads.map((thread) => (
                        <tr key={thread.id} className="hover:bg-gray-50">
                          <td className="px-6 py-4 whitespace-nowrap">
                            <Link
                              href={`/community/thread/${thread.id}`}
                              className="text-blue-600 hover:text-blue-800 font-medium"
                            >
                              {thread.title}
                            </Link>
                          </td>
                          <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                            {/* SECURITY: Display anonymized ID only */}
                            {thread.authorId}
                          </td>
                          <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                            {thread.replyCount}
                          </td>
                          <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                            {new Date(thread.createdAt).toLocaleDateString()}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>

                {/* Pagination Placeholder */}
                <div className="mt-6 flex justify-center">
                  <div className="bg-white rounded-lg shadow-md p-4">
                    <p className="text-sm text-gray-600">
                      Page {currentPage} (Pagination to be implemented)
                    </p>
                  </div>
                </div>
              </>
            )}
          </div>
        </div>
      </div>
    </>
  );
}

